spring:
  application:
    name: microservice-pedidos
  datasource:
    url: jdbc:postgresql://localhost:5555/ms_pedidos
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8083

order-management-microservices:
  microservice-produtos:
    url: http://localhost:8084
  microservice-clientes:
    url: http://localhost:8082
  kafka:
    topics:
      pedido-pago: order-management-microservices_pedidos-pagos
      pedido-faturado: order-management-microservices_pedidos-faturados
      pedido-enviado: order-management-microservices_pedidos-enviados

webhook:
  payments:
    api-key: ${WEBHOOK_PAYMENTS_API_KEY:chave-secreta-local}