spring:
  application:
    name: microservice-pedidos
  datasource:
    url: jdbc:postgresql://localhost:5555/ms_pedidos
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8083

order-management-microservices:
  microservice-produtos:
    url: http://localhost:8084
  microservice-clientes:
    url: http://localhost:8082

webhook:
  payments:
    api-key: ${WEBHOOK_PAYMENTS_API_KEY:chave-secreta-local}